### ISSUE TITLE
Task 1: Getting things Ready

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#1]
# Task 1: Getting to know GIT and repositories
## Objective:
Create a new repository on GitHub and push files to it using Git.

## Task Overview

- Learn how to create a repository on GitHub.
- Initialize a local Git repository and connect it to the remote repository.
- Push files from your local machine to the remote repository.

## Task Details

1. Watch a tutorial video or read an article on `using git as a version control`
2. Sign in to your GitHub account.
3. Click on the "+" icon in the top-right corner and select "New repository" from the dropdown menu.
4. Provide a name for your repository (e.g., "frontend-bootcamp-tasks") and an optional description.
5. Choose the visibility (public or private) for your repository.
6. Optionally, select the option to initialize the repository with a README file.
7. Click on the "Create repository" button to create the repository on GitHub.

Now, let's move to the local machine:

Open a terminal or command prompt and navigate to your project directory.
Initialize a new Git repository in your project directory using the command:

`git init`

Add the files you want to push to the repository. For example, if you have an HTML file called "index.html" and a CSS file called "styles.css" in your project directory,

Style and create anything you wish for which contains at least 10 element tags like div , h1 , p , a , all the other try to style each and every one of them in different variants

 use the following command to add them:

`git add .`

Commit the changes with a descriptive message using the command:

`git commit -m "Initial commit"`
Connect your local repository to the remote repository on GitHub using the following command:

`git remote add origin https://github.com/your-username/frontend-bootcamp-tasks.git`

Push the changes to the remote repository using the command:
`git push origin master`

**Verify that the files have been pushed to your GitHub repository by visiting the repository's page on GitHub.**

## Task Submission

Take a screenshot of your GitHub repository showing the pushed files.
Share the screenshot on the issues comment of this issue.

**Comment by satshree** [comment]
<img width="1552" alt="Screenshot 2024-02-27 at 12 47 59 PM" src="https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/1b1907e2-f045-4089-9a93-0a31b380684d">

**Comment by satshree** [comment]
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/284a04ae-df59-46d0-9c6e-9e235f7ea1cf)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/3aaed07e-5b09-4a1a-a611-1ba3f3dfc1d8)

**Comment by sonamLama22** [comment]
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/bce83ebf-0a8a-4440-bf5f-b274d38fcbea)

**Comment by sherpa2025** [comment]
**New Branch in Yogesh Repo**
![task1](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/69315caf-2257-4b10-94af-2b448010f7b6)


**New Repository Task**
![New Repo](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/6a15c067-a7d5-4d4b-892d-9bef055b912f)

**Comment by sonamLama22** [comment]
# Task 1 - sonam


![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/3aa81d1e-e252-4c23-a38b-e9dbe9a2b5d1)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/0bba7c4f-a3a1-4df9-960e-cbbb06e3cd4b)

**Comment by gsajan21** [comment]
https://github.com/gsajan21/frontend-practice-session.git

![Screenshot 2024-02-27 at 11 28 23 AM](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/cd0c3ac1-c6bc-495a-87ab-8550b7ee6b00)

**Comment by Aakash-codes-git** [comment]
![Screenshot (16)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/fc1834dd-9a41-4ba5-83c8-b8f5bb0de4e8)

**Comment by Aakash-codes-git** [comment]
![Screenshot (18)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/0a3647bc-0c7c-4607-85fd-3a9857f019be)

**Comment by Aakash-codes-git** [comment]
![Screenshot (16)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/3f4036c1-e3ac-49af-98ce-6903db9fe367)

**Comment by Aakash-codes-git** [comment]
![Screenshot (18)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/53a7d7d8-fb5d-44b4-8f39-d1ecdec4ffca)

**Comment by Aakash-codes-git** [comment]
![Screenshot (19)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/4d7e239e-bbc7-4565-a7b7-71459f3d8489)

**Comment by mwdorji13** [comment]
![bfs](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/98498302/94695bdf-69ad-496b-bbcc-896336f2ef30)
![bfs2](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/98498302/b369558f-73f7-4634-8ddb-d33d167ddfdc)

**Comment by Nirjala123** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/nirjala-task1?files=1

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/f147a87d-490b-41f7-a189-95690e80a379)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/0870daea-fbc9-4b0b-93de-0952121d93f8)
