### ISSUE TITLE
Project 2: Portfolio

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#13]
**Student Portfolio Showcase Task**

**Task Description:**
You are tasked with creating a portfolio website for showcasing a student's completed projects. The portfolio should be built using React for the frontend, Redux for state management, and a UI library of your choice for designing the user interface. The goal is to create an attractive and functional portfolio that effectively displays the student's projects.

**Requirements:**

**Frontend (React with Redux):**
- Use React for building the user interface and Redux for state management.
- Choose a suitable UI library (e.g., Material-UI, Ant Design, Chakra UI) to enhance the design and user experience.

1. **Home Page:**
   - Create a home page that introduces the student and provides a brief overview of their skills and interests.
   - Include a navigation bar to access different sections of the portfolio.

2. **Projects Showcase:**
   - Implement a section to display a grid or list of projects.
   - Each project should have a title, description, image, and a link to view more details.
   - Use Redux to manage the project data and state.

3. **Project Details:**
   - Implement a detailed view for each project.
   - Display project details such as a longer description, technologies used, and any other relevant information.
   - Provide links to the project's live demo and GitHub repository.

4. **Contact Information:**
   - Create a contact section that includes the student's email address, LinkedIn profile, GitHub profile, etc.

**Additional Considerations:**

1. **UI Design:**
   - Utilize the chosen UI library's components for consistent and visually appealing design.
   - Focus on creating a clean and modern design that enhances the portfolio's presentation.

2. **State Management (Redux):**
   - Implement Redux to manage the state related to projects and any global state requirements.

3. **Responsive Design:**
   - Ensure that the portfolio is responsive and works well on different screen sizes and devices.

4. **Navigation:**
   - Implement smooth navigation between different sections of the portfolio.

**Submission:**
Provide the source code for the React application along with detailed instructions to set up and run the application locally.

**Evaluation Criteria:** 
Your submission will be evaluated based on the functionality, code quality, user experience, design aesthetics, and adherence to the provided requirements. Aim to create an engaging and professional student portfolio showcase that effectively highlights the completed projects.

**Comment by satshree** [comment]
https://github.com/satshree/portfolio/tree/master

**Comment by gsajan21** [comment]
https://sgurung.netlify.app/

https://github.com/gsajan21/team-project2

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/85a83358-3273-4dd0-8c89-a8ede6ea62e5)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/56795de7-446c-42bd-ae6d-80e4fe2b395e)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/b1579338-8fa2-486f-bde8-860234f9b5a2)

**Comment by sherpa2025** [comment]
**Github Repo: https://github.com/sherpa2025/portfolio**

**Website Link:** : https://nsherpaportfolio.netlify.app/

**Comment by Nirjala123** [comment]
https://incredible-beignet-2218fa.netlify.app/
https://github.com/Nirjala123/portfolio

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/ecf7ceb7-107f-4e74-94b5-f9424cde59eb)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/7a0feb83-9d0a-4de4-9a9f-3e89187b6b33)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/e566a3bc-91b6-4728-b854-9e53e0798d74)

**Comment by aashirwad43** [comment]
Team 1: Aashirwad and Sonam

Github: https://github.com/sonamLama22/portfolio-takeo/tree/dev
Live Website: https://portfolio-takeo.netlify.app/
