### ISSUE TITLE
Project : Social Media Dashboard

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#14]
**Social Media Dashboard Task**

**Task Description:**
You are assigned to create a Social Media Dashboard using React. The dashboard should allow users to manage their posts by updating, deleting, and creating new posts. The application should provide an intuitive and user-friendly interface for managing posts.

**Requirements:**

**Frontend (React):**
- Use React to build the frontend of the Social Media Dashboard.
- Create a visually appealing and responsive user interface.

1. **Post List:**
   - Display a list of posts retrieved from a static data source (JSON) initially.
   - Each post should show the title, content, and date of creation.
   - Provide buttons to edit and delete each post.

2. **Create Post:**
   - Implement a form to create a new post.
   - The form should include fields for the post title and content.
   - Upon submission, the new post should be added to the post list.

3. **Edit Post:**
   - Implement an edit feature for each post.
   - Clicking the edit button should open a modal with the current post details.
   - Allow users to modify the title and content.
   - Upon saving changes, update the post in the list.

4. **Delete Post:**
   - Provide a delete button for each post.
   - When clicked, prompt the user for confirmation before deleting the post.
   - Remove the post from the list after confirmation.

**Additional Considerations:**

1. **User Experience:**
   - Implement smooth animations and transitions.
   - Provide feedback messages for successful and failed actions.

2. **UI Design:**
   - Use a CSS framework (e.g., Bootstrap, Tailwind CSS) or custom styles for styling the components.

3. **Error Handling:**
   - Handle errors gracefully and display error messages to users if needed.

4. **State Management:**
   - Use React's state management (Context API or Redux) for managing the post list and modal state.

**Submission:**
Provide the source code for the React application along with any necessary instructions to set up and run the application locally.

**Evaluation Criteria:**
Your submission will be evaluated based on the functionality, code quality, user experience, and adherence to the provided requirements. Focus on creating a polished and user-friendly Social Media Dashboard.

**Comment by gsajan21** [comment]
https://github.com/gsajan21/twitter-clone



![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/18cd1c59-f258-4e8b-b97a-c53a771841a8)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/62014448-1fe9-409d-be82-605017ff9c33)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/c7beda47-504c-40f2-90bf-bce9b1d68b4b)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/a44304da-3eed-4c92-9098-4dfdfc89d734)

**Comment by satshree** [comment]
https://github.com/satshree/social-media/tree/master

**Comment by Nirjala123** [comment]
https://github.com/Nirjala123/social-media-dashboard/tree/nirjala

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/334fba33-d690-40e6-b089-ba244896672d)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/811b9e67-6710-4ecd-a169-56af63f91e82)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/0c16659e-a33e-46f7-94c3-d70b9a65f17e)
![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/05067a03-4c02-459a-9de9-82514f8476dc)

**Comment by sonamLama22** [comment]
https://github.com/aashirwad43/socialmedia-dashboard

**Comment by sherpa2025** [comment]
**Github Repo: https://github.com/sherpa2025/social-media-dashboard**
![1(Main Dashboard)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/f838f27a-e39b-4cf0-a1e7-5620175b8559)
![2(New Post)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/08b8c8a4-bb38-48ec-ab7b-1cd5bcfa2c9e)
![3(Edit Delete Icon)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/88b5ab3a-1456-436b-b9be-724394f3b4fe)
![4(Edit done)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/f510b26b-7d69-4507-a5a1-0a7c7fbeb1bd)
![5(Delete)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/748caf21-0b08-49a8-9414-b8c8c345c570)

**Comment by aashirwad43** [comment]
Team 1: Aashirwad and Sonam

Github: https://github.com/aashirwad43/socialmedia-dashboard
Live Website: https://socialmedia-dashboard-takeo.netlify.app/
