### ISSUE TITLE
Task 2 : CSS in Vite

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#3]
# **Task 2: CSS Styling in a React Project with Vite**

## Task Overview

- Understand the basics of CSS styling and JavaScript variables.
- Apply CSS styles to React components using class names and inline styles.
- Utilize JavaScript variables to enhance interactivity in a React project.

### - Review CSS Styling and JavaScript Variables.
Watch a tutorial video or read articles on CSS styling and JavaScript variables.
<a href="https://www.youtube.com/watch?v=XgSjoHgy3Rk&ab_channel=ProgrammingwithMosh"> Youtube video to learn about variables</a>
<a href="https://www.youtube.com/watch?v=WuvujA5facU&ab_channel=DanielWood">CSS styling methodology</a>
Familiarize yourself with the basics of CSS selectors, properties, and values.
Understand the concept of JavaScript variables and their usage.

### - Set Up a React Project with Vite.
You can also use the normal way that we used to create the vite react project with `npx create-vite@latest project_name`
or
Open a terminal or command prompt.
Create a new directory for your project:
`
mkdir react-styling
cd react-styling
`
Set up a new React project using Vite by running the following command:
`npm init vite@latest`

### - Apply CSS Styling.

1. Open your project in a code editor.
2. Identify a React component (e.g., App.js or any other component in the src directory) where you want to apply CSS styles.
3. Add CSS class names to the HTML elements within the component to target them with CSS.
4. Create a new CSS file (e.g., `styles.css`) in the src directory and write CSS styles to target the class names used in the component.
5. Import the CSS file in the component file (e.g.,` import './styles.css'`;) to apply the styles.
6. Try to make the design responsive and fluid in nature.
7. Try to create at least 10 components (button , link , image, containers (div) , etc) and add designs with css

Note : Use of proper Stylings UI should be applied padding, margin , border, color, background height , width and the use of px , rem and percentage (%) should be shown in the screenshot submission

 ### - Test and Refine

1. Start the development server by running the following command in the project directory:`npm run dev`
2. Open your web browser and navigate to the provided local development server URL (e.g., http://localhost:3000).
3. Verify that the CSS styles are applied to the targeted elements.

## Task Submission
Take a screenshot of the rendered semantic components in the browser.
Share the screenshot of the output and the code that you have written in the issue comment box.
Don't forget to mention GitHub URL and your name in the comment section.

**Comment by satshree** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/satshree-task1

**Comment by satshree** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/satshree-task1

Satshree Shrestha

GitHub username: satshree

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/12a32fa2-561f-4012-9ce9-57e715b7f60e)

**Comment by satshree** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/satshree-task2

GitHub username: satshree

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/bed1e054-d076-45f0-96c8-870b2db2ae61)

**Comment by sonamLama22** [comment]
# Task 2 Sonam
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/sonam-task2

<img width="1067" alt="Screenshot 2024-02-28 191326" src="https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/8a19f065-eff1-4960-9f07-64474459d6a0">

**Comment by sherpa2025** [comment]
**Task 2: Nima
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/nima-task2**
![Task2](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/289dc382-4ce0-4193-8bc0-8d12e1b6e963)

**Comment by dhawasangbolama2** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/dhawa-task2

![screenshot](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/57231698/a6d9c772-5269-4793-832f-05e4603b1f85)

**Comment by Aakash-codes-git** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/Aakash-task2

![Screenshot (21)](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/157153561/d739ca06-9c21-4670-aed8-6197a6c1ea54)

**Comment by aashirwad43** [comment]
Task 2: Aashirwad

https://github.com/yogeshtakeo/BFS_45_Repositary/tree/aashirwad-task2



![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/54662467/0f9f2dcd-d5ff-4929-8b2f-36da0b766548)

**Comment by Nirjala123** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/nirjala-task2?files=1

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/b7d5fc43-3cc9-43ad-8036-b6afc26cf0f0)

**Comment by mwdorji13** [comment]
![task2](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/98498302/cf88d13a-28c0-4257-8107-b81c10b952b7)

**Comment by gsajan21** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/sajan-task2

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/8e195c25-e9e8-411f-8f37-2cdada6e520f)
