### ISSUE TITLE
Task 5 : TODO with css

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#7]
## Task: Create a Todo List Application

**Objective:** Build a simple todo list application using React to manage tasks.

### Task Overview
- Set up a new React project using a tool of your choice (e.g., Vite, Create React App, etc.).
- Implement the functionality to add, edit, and delete tasks in the todo list.
- Style the application using native CSS or a CSS framework of your choice.

### Task Details
1. **Project Setup:**
   - Set up a new React project using a tool of your choice.
   - Create a new component called `TodoList` to manage the todo list.

2. **Render a List of Tasks:**
   - Create a state variable to store the list of tasks (an array of objects with properties like `id`, `title`, `completed`, etc.).
   - Render the list of tasks in the `TodoList` component using JSX and the array's `map` method.

3. **Add New Tasks:**
   - Create a form in the `TodoList` component to add new tasks.
   - Implement an input field for entering task titles and a submit button.
   - Handle the form submission event to add the new task to the list of tasks.

4. **Edit Tasks:**
   - Implement functionality to edit tasks in the todo list.
   - Add an edit button or an inline editing feature for each task.
   - When the user clicks the edit button or triggers the inline editing, allow them to modify the task title.
   - Update the corresponding task in the list of tasks when the editing is completed.

5. **Delete Tasks:**
   - Implement functionality to delete tasks from the todo list.
   - Add a delete button for each task in the list.
   - Handle the delete button click event to remove the task from the list of tasks.

6. **Style the Application:**
   - Apply styles to the todo list application using native CSS or a CSS framework of your choice.
   - Design a clean and user-friendly interface for adding, editing, and deleting tasks.
   - Make the application visually appealing and responsive.

7. **Test and Refine:**
   - Start the development server and run the React project.
   - Verify that tasks can be added, edited, and deleted successfully.
   - Test different scenarios, such as adding multiple tasks, editing existing tasks, and deleting tasks, to ensure the functionality works as expected.

##  Task Submission
Take a screenshot of the web browser displaying the rendered React component .
Share the screenshot
Optionally, submit the code files (App.js and any other relevant files) for review with the GitHub Repository.

**Comment by satshree** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/satshree-task5

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/1105b926-0794-476b-a51f-3031e3ef1cac)

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/a98ce019-ec31-4419-9c71-fd4a8816497c)

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/40155624/8f080952-1789-4111-8dd1-75c53a15afa1)

**Comment by gsajan21** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/sajan-task5


![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/49371a7d-8246-415c-80ee-f46cbf6f895a)

**Comment by dhawasangbolama2** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/dhawa-task4

![Screenshot 2024-03-06 at 4 19 40 AM](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/57231698/b75b573a-f479-467d-b029-a4ad7d3fbaa0)

**Comment by Nirjala123** [comment]
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/nirjala-task5

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/7266e33b-fbc7-488d-af8c-eb928ac796cd)

**Comment by sherpa2025** [comment]
**Nima: Task5
https://github.com/yogeshtakeo/BFS_45_Repositary/tree/nima-task5**
![Todo](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/79430796/95946215-1f85-4af7-9549-aad6507ad036)

**Comment by sonamLama22** [comment]
## Task-5 Sonam

https://github.com/yogeshtakeo/BFS_45_Repositary/tree/sonam-task5


<img width="474" alt="Screenshot 2024-03-07 095133" src="https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/04c8888f-6c8d-4c88-83b5-fc2a88477df1">

<img width="467" alt="Screenshot 2024-03-07 095235" src="https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/70719553-2178-4e4d-8b57-de9ceef80044">

<img width="460" alt="Screenshot 2024-03-07 095247" src="https://github.com/yogeshtakeo/BFS_45_Repositary/assets/74273235/3d59e53e-0109-4882-8d04-957d2220898a">
