### ISSUE TITLE
Project 1: Task Manager

### ISSUE THREAD

**Issue by yogeshtakeo** [yogeshtakeo/BFS_45_Repositary#8]
### **Task 11: Build a Simple Task Manager List Application Using React and Native CSS Styling (Single File)**

**Project Objective:** Build a simple Task list application using React and style it using native CSS.

## Task Overview

1. Create a React project structure in a single file.
3. Style the application using native CSS to enhance its visual appearance.

### Project Setup:

1. Set up a new React project in a single file by importing the necessary React modules.
2. Create a functional component called TodoApp to serve as the main container for the Task list.

### Implement Task List Functionality:

1. In the TodoApp component, set up a state variable to store the list of tasks.
2. Implement functionality to add new tasks by capturing input from a API `https://jsonplaceholder.typicode.com/todos/` and updating the state accordingly.

### Style the Task List:

1. Use native CSS to style the Task list application.
2. Apply styling to the TodoApp component to define the layout and appearance of the overall list.
3. Style each task item to differentiate completed and pending tasks.
4. Apply appropriate styles to the input field and buttons to enhance their visual appearance.

### Test and Refine:

1. Start the development server and run the React project.
2. Verify that the Task list application functions as expected.
3. Ensure the application is visually appealing and the styling is well-applied.

##  Task Submission
Take a screenshot of the web browser displaying the rendered React component .
Share the screenshot
Optionally, submit the code files (App.js and any other relevant files) for review with the GitHub Repository.

**Comment by satshree** [comment]
https://github.com/satshree/task-manager-todo

**Comment by Nirjala123** [comment]
https://github.com/Nirjala123/Project-1--Task-Manager-Nirjala-and-Menda-/tree/typescript-todo

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/23175457/a2433c7f-7af7-4728-860b-2ac56d144ee8)

**Comment by aashirwad43** [comment]
Aashirwad & Sonam -  Team 1

https://github.com/aashirwad43/task-manager

**Comment by gsajan21** [comment]
https://teamtaskapp.netlify.app/

https://github.com/gsajan21/team-project-task

![Image](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/22806266/fea67e48-7d49-4749-9849-80ff367815bc)

**Comment by dhawasangbolama2** [comment]
team 5 Dhawa and Aakash
![Screenshot 2024-03-12 at 9 08 58 PM](https://github.com/yogeshtakeo/BFS_45_Repositary/assets/57231698/815db13e-ea7e-41cf-bcf0-9eb2155cb9b2)

[task-manager-team5.netlify.app](https://task-manager-team5.netlify.app/)
